Update test_and_deploy.yml

diff --git a/.github/workflows/test_and_deploy.yml b/.github/workflows/test_and_deploy.yml
--- a/.github/workflows/test_and_deploy.yml
+++ b/.github/workflows/test_and_deploy.yml
@@ -30,12 +30,16 @@ jobs:
 
     - name: Validate Nginx syntax
       run: |
-        # Временно заменяем backend на localhost для проверки синтаксиса
         sed 's/backend/localhost/' nginx/app.conf > nginx/temp.conf
         docker run --rm \
           -v $(pwd)/nginx/temp.conf:/etc/nginx/conf.d/default.conf \
           nginx:alpine nginx -t
         rm nginx/temp.conf
+
+    - name: Validate HTML
+      run: |
+        sudo apt-get install -y tidy
+        tidy -q -e nginx/index.html || echo "HTML validation failed! Fix markup errors."
 
   build-and-deploy:
     needs: test
@@ -66,7 +70,6 @@ jobs:
     - name: Deploy
       run: |
         scp -o StrictHostKeyChecking=no ./docker-compose.yml root@${{ secrets.PROD_SERVER_IP }}:/root/app/
-
         ssh -o StrictHostKeyChecking=no root@${{ secrets.PROD_SERVER_IP }} << 'EOF'
           cd /root/app
           docker-compose down
